---
- name: Install stow in Debian-based distros 
  import_tasks: linux.yml
  when: ansible_distribution == "Pop!_OS" or ansible_distribution == "Ubuntu"

- name: Remove files that will conflict with Stow
  loop:
    - .zshrc
  ansible.builtin.file:
    path: "{{ home }}/{{ item }}"
    state: absent

- name: Delete Previous stowed folders
  loop:
    - bin
    - nvim
    - tmux
    - tmuxp
    - zsh
  args:
    chdir: "{{ dotfiles }}/configs"
  shell: "stow -D {{ item }} -t {{ home }} --verbose=2"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'

- name: Run stow
  become_user: "{{ username }}"
  loop:
    - bin
    - nvim
    - tmux
    - tmuxp
    - zsh
  args:
    chdir: "{{ dotfiles }}/configs"
  shell: "stow {{ item }} -t {{ home }} --verbose=2"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'
