#!/usr/bin/env bash

STOW_FOLDERS="bin,nvim,tmux,tmuxp,zsh"

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"

    # first unstow the folder to clean up
    stow --delete $folder --target=$HOME

    # then re-symlink it
    stow $folder --target=$HOME
done
popd
