---
- name: Create nvim directory if it does not exist
  become: yes
  ansible.builtin.file:
    path: /bin/nvim
    state: directory
    mode: '0755'

- name: Remove Existing install dir 
  become: yes
  ansible.builtin.file:
    state: absent 
    path: /bin/nvim/squashfs-root
  when: "force_install" 

- name: Remove 
  become: yes
  ansible.builtin.file:
    path: /bin/nvim/nvim.appimage
    state: absent 
  when: "force_install" 

- name: Download nvim Appimage 
  become: yes
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    dest: /bin/nvim/nvim.appimage
    owner: "{{ username }}"
    group: "{{ username }}" 
    mode: u+x
  when: "force_install"

- name: Extract Appimage
  become: yes
  shell: ./nvim.appimage --appimage-extract
  args:
    chdir: /bin/nvim
  when: "force_install"

- name: Remove Appimage
  become: yes
  ansible.builtin.file:
    state: absent 
    path: /bin/nvim/nvim.appimage
  when: "force_install"


- name: Create Symbolic link for Nvim appimage
  become: yes
  ansible.builtin.file:
    src: /bin/nvim/squashfs-root/AppRun
    dest: /bin/nvim/nvim.appimage
    state: link
