services:
  # POP!_OS
  pop_os-dotfiles-direct:
    build:
      context: ../
      dockerfile: docker/direct.Dockerfile
      args:
        IMAGE: nycticoracs/pop_os:latest 
    container_name: pop_os-dotfiles-direct
    user: lcontreras
    tty: true
    entrypoint: /bin/zsh
    environment:
      - TERM=xterm-256color

  pop_os-dotfiles-indirect:
    build:
      context: ../
      dockerfile: docker/indirect.Dockerfile
      args:
        IMAGE: nycticoracs/pop_os:latest 
    container_name: pop_os-dotfiles-indirect
    user: lcontreras
    tty: true
    entrypoint: /bin/zsh
    environment:
      - TERM=xterm-256color

  # UBUNTU
  ubuntu-dotfiles-direct:
    build:
      context: ../
      dockerfile: docker/direct.Dockerfile
      args:
        IMAGE: ubuntu:latest
    container_name: ubuntu-dotfiles-direct
    user: lcontreras
    tty: true
    entrypoint: /bin/zsh
    environment:
      - TERM=xterm-256color

  ubuntu-dotfiles-indirect:
    build:
      context: ../
      dockerfile: docker/indirect.Dockerfile
      args:
        IMAGE: ubuntu:latest
    container_name: ubuntu-dotfiles-indirect
    user: lcontreras
    tty: true
    entrypoint: /bin/zsh
    environment:
      - TERM=xterm-256color
