# ENV Variables
username: "{{ ansible_user_id }}"
git_username: "lcontreras21"
git_email: "luiscontrerasorendain@gmail.com"
home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
default_config: default(home) + '/.config'
config: "{{ lookup('ansible.builtin.env', 'XDG_CONFIG_HOME') | default(default_config) }}"
dotfiles: "{{ home }}/.dotfiles" 

# Package Versions
golang_version: "1.22.3"
nodejs_version: "14.x"
