session_name: BEAM
start_directory: ~/ClearlyEnergy/BEAM
environment:
  DJANGO_SETTINGS_MODULE: config.settings.dev
shell_command_before: "conda activate BEAM_UPDATE"
windows:
  - window_name: Django
    panes:
      - shell_command:
        - ./bin/start-beam.sh 
  - window_name: BEAM
    panes:
      - shell_command:
        - vim .
