---
# https://github.com/tmux-plugins/tpm/blob/master/docs/automatic_tpm_installation.md
- name: Make TPM Directory
  become: true
  file:
    path: "{{ config }}/tmux/plugins/tpm"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0777'
    state: directory

- name: Clone TPM Repo
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: '{{ config }}/tmux/plugins/tpm'
    depth: 1

- name: Install TPM Plugins
  args:
    chdir: "{{ config }}/tmux/plugins/tpm/bin"
  shell: './install_plugins'
  register: install_plugin_output
  when: "force_install"

- name: Symlink TMUX Git Status statusline
  file:
    src: "{{ config }}/tmux/git_status.sh"
    dest: "{{ config }}/tmux/plugins/tmux/custom/git_status.sh"
    state: link
