---
# INITIALIZATION
- name: Set default starting branch to main instead of master
  git_config:
    name: init.defaultBranch 
    scope: global
    value: "main"

# USER
- name: user.name for git config
  git_config:
    name: user.name
    scope: global
    value: "{{ git_username }}"

- name: user.email for git config
  git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"

# SAFETY
- name: Silence all safe.directory warnings
  git_config:
    name: safe.directory
    scope: global
    value: "*"

# CORE
- name: Set default editor to Neovim (btw)
  git_config:
    name: core.editor 
    scope: global
    value: "vim"

- name: Core - autocrlf 
  git_config:
    name: core.autocrlf 
    scope: global
    value: "input"

- name: Core - autolf 
  git_config:
    name: core.autolf 
    scope: global
    value: "input"

- name: Core - whitespace 
  git_config:
    name: core.whitespace 
    scope: global
    value: "trailing-space"

# FETCH
- name: Set fetch to auto prune remote tracking branches that have been deleted
  git_config:
    name: fetch.prune 
    scope: global
    value: "true"

# CREDENTIALS
- name: Credential - store
  git_config:
    name: credential.helper 
    scope: global
    value: "store"

# SUBMODULES
- name: Set submodule status to show more info
  git_config:
    name: status.submoduleSummary
    scope: global
    value: "true"

- name: Set submodule diff to show more info
  git_config:
    name: diff.submodule
    scope: global
    value: "log"

- name: Set git to recurse into submodules
  git_config:
    name: submodule.recurse
    scope: global
    value: "true"

# BRANCHES
- name: Set branch sort to be recently used
  git_config:
    name: branch.sort 
    scope: global
    value: "committerdate"
