---
- name: Download go tar file
  become: true
  command: wget https://go.dev/dl/go{{ golang_version }}.linux-amd64.tar.gz

- name: Delete previous installation
  become: true
  command: rm -rf /usr/local/go

- name: Extract and move new go folder to /usr/local
  become: true
  command: tar -C /usr/local -xzf go{{ golang_version }}.linux-amd64.tar.gz

- name: Delete downloaded tar file
  become: true
  shell: rm -rf go{{ golang_version }}.linux-amd64.tar.gz*
